In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import os



from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC 
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.feature_selection import SelectKBest, f_classif
from imblearn.over_sampling import SMOTE

In [2]:
data_location = r"D:\Data science Course\My projects\Guvi projects\vocal_gender_features_new\vocal_gender_features_new.csv"
df = pd.read_csv(data_location)
df.head()

mean_spectral_centroid  std_spectral_centroid  mean_spectral_bandwidth  \
0             2247.331739            1158.537748              1870.415462   
1             1790.719889             996.554825              1757.898617   
2             1977.923363            1010.148667              1747.099555   
3             2037.765550            1311.440630              1745.224852   
4             1739.383829            1092.623322              1623.135563   

   std_spectral_bandwidth  mean_spectral_contrast  mean_spectral_flatness  \
0              370.405241               21.440710                0.036879   
1              410.710318               21.513383                0.018936   
2              461.458379               20.476283                0.032616   
3              419.056484               19.516014                0.028482   
4              450.088465               20.260620                0.025737   

   mean_spectral_rolloff  zero_crossing_rate  rms_energy  mean_pitch  ...  \
0            4419.438073            0.169241    0.082552   1592.1033  ...   
1            3635.742188            0.108068    0.055477   1112.6351  ...   
2            3873.291016            0.144633    0.060388   1557.5225  ...   
3            3826.584507            0.148933    0.029559   1481.0868  ...   
4            3452.903892            0.117961    0.069078   1424.5352  ...   

   mfcc_9_std  mfcc_10_mean  mfcc_10_std  mfcc_11_mean  mfcc_11_std  \
0   21.736240      2.303085     8.983318    -17.410305     9.115154   
1   13.937135     -0.953942    10.831742     -0.088775    10.297690   
2   14.900779      0.260098    14.031009     -0.420670    10.810292   
3   15.957924     -1.486122    14.461978     -8.479608    12.550333   
4   15.105562     -3.366364    13.943447     -6.561539    11.944948   

   mfcc_12_mean  mfcc_12_std  mfcc_13_mean  mfcc_13_std  label  
0      0.301804    10.452693     -3.080832    10.146248      0  
1     -7.281142    10.926579     -0.450248     8.489134      0  
2     -0.199829    11.986182      3.372986     9.285437      0  
3      3.997028     9.912608     -6.946966    10.574301      0  
4      1.410639    13.110976     -3.252258     9.866687      0  

[5 rows x 44 columns]

In [3]:
df.isnull().sum()

mean_spectral_centroid     0
std_spectral_centroid      0
mean_spectral_bandwidth    0
std_spectral_bandwidth     0
mean_spectral_contrast     0
mean_spectral_flatness     0
mean_spectral_rolloff      0
zero_crossing_rate         0
rms_energy                 0
mean_pitch                 0
min_pitch                  0
max_pitch                  0
std_pitch                  0
spectral_skew              0
spectral_kurtosis          0
energy_entropy             0
log_energy                 0
mfcc_1_mean                0
mfcc_1_std                 0
mfcc_2_mean                0
mfcc_2_std                 0
mfcc_3_mean                0
mfcc_3_std                 0
mfcc_4_mean                0
mfcc_4_std                 0
mfcc_5_mean                0
mfcc_5_std                 0
mfcc_6_mean                0
mfcc_6_std                 0
mfcc_7_mean                0
mfcc_7_std                 0
mfcc_8_mean                0
mfcc_8_std                 0
mfcc_9_mean                0
mfcc_9_std    

In [4]:
df[df.duplicated()]

mean_spectral_centroid  std_spectral_centroid  mean_spectral_bandwidth  \
4153              1412.128910             920.473327              1414.160017   
4156              1350.984280             697.583027              1405.091432   
4159              1700.003436            1139.849988              1563.882152   
4162              1603.435295            1098.400082              1504.251367   
4165              2232.938291            1631.809654              1651.055700   
...                       ...                    ...                      ...   
16039             1831.290901            1095.657669              1507.126905   
16046             1674.069934             689.702062              1595.336488   
16053             1729.333727             924.972131              1511.611165   
16060             2390.192041            1371.257338              1654.646816   
16067             1775.489511            1048.531356              1600.576316   

       std_spectral_bandwidth  mean_spectral_contrast  mean_spectral_flatness  \
4153               622.996586               22.248629                0.032454   
4156               497.950051               21.674845                0.025402   
4159               591.271918               21.496923                0.024522   
4162               539.193703               22.398801                0.026613   
4165               612.490155               20.603783                0.047873   
...                       ...                     ...                     ...   
16039              441.370106               20.577582                0.023060   
16046              350.695179               19.293286                0.032054   
16053              379.952701               19.899175                0.024843   
16060              447.120204               20.030245                0.037977   
16067              460.229019               19.870907                0.031633   

       mean_spectral_rolloff  zero_crossing_rate  rms_energy  mean_pitch  ...  \
4153             2865.740741            0.062500    0.133391   1282.4385  ...   
4156             2785.982572            0.086581    0.102512   1293.0490  ...   
4159             3284.975962            0.130687    0.115451   1374.5704  ...   
4162             3160.000000            0.102539    0.124267   1408.1073  ...   
4165             3923.056723            0.213629    0.101999   1615.0890  ...   
...                      ...                 ...         ...         ...  ...   
16039            3381.093750            0.161582    0.063989   1519.1984  ...   
16046            3384.114583            0.105499    0.077688   1682.6837  ...   
16053            3433.225236            0.123876    0.086999   1576.6437  ...   
16060            4174.310065            0.195306    0.074226   1775.7415  ...   
16067            3429.788961            0.131088    0.065542   1761.5902  ...   

       mfcc_9_std  mfcc_10_mean  mfcc_10_std  mfcc_11_mean  mfcc_11_std  \
4153    13.418416     -6.713120    10.089062     -9.737516    10.000673   
4156    13.047665     -6.953734    10.334755     -7.955184     7.243159   
4159    14.525292     -3.543442     7.883509    -13.231023    12.112495   
4162    16.980540     -6.776709    10.832165    -12.774789     9.733416   
4165    12.989914     -1.322290    11.655929     -8.510401     8.701939   
...           ...           ...          ...           ...          ...   
16039   13.705769      2.318734    15.737608    -12.732199     9.730263   
16046   10.386293     -4.007985    17.626696     -5.365382    10.082510   
16053   10.382106      5.488963    16.886936    -16.970497    11.435887   
16060   13.382373      5.654511    17.184233    -13.719124     9.047874   
16067   11.446008     -0.755797    18.553822    -12.217823     9.455145   

       mfcc_12_mean  mfcc_12_std  mfcc_13_mean  mfcc_13_std  label  
4153      -3.583986     7.366380     -7.657676     8.581247      0  
4156      -6.843229     9.650276     -7.887499   

In [5]:
df = df.drop_duplicates()
df

mean_spectral_centroid  std_spectral_centroid  mean_spectral_bandwidth  \
0                 2247.331739            1158.537748              1870.415462   
1                 1790.719889             996.554825              1757.898617   
2                 1977.923363            1010.148667              1747.099555   
3                 2037.765550            1311.440630              1745.224852   
4                 1739.383829            1092.623322              1623.135563   
...                       ...                    ...                      ...   
16143             1879.614568            1092.394432              1802.821290   
16144             1810.603695            1124.628905              1829.785209   
16145             1820.216958            1197.520780              1770.716715   
16146             1636.619660            1055.832051              1747.968472   
16147             1604.684012            1023.600709              1702.723635   

       std_spectral_bandwidth  mean_spectral_contrast  mean_spectral_flatness  \
0                  370.405241               21.440710                0.036879   
1                  410.710318               21.513383                0.018936   
2                  461.458379               20.476283                0.032616   
3                  419.056484               19.516014                0.028482   
4                  450.088465               20.260620                0.025737   
...                       ...                     ...                     ...   
16143              479.751352               19.930251                0.017547   
16144              491.274993               19.115077                0.017356   
16145              509.906085               19.506173                0.015819   
16146              500.649272               19.118411                0.014007   
16147              555.133862               19.279221                0.016868   

       mean_spectral_rolloff  zero_crossing_rate  rms_energy  mean_pitch  ...  \
0                4419.438073            0.169241    0.082552   1592.1033  ...   
1                3635.742188            0.108068    0.055477   1112.6351  ...   
2                3873.291016            0.144633    0.060388   1557.5225  ...   
3                3826.584507            0.148933    0.029559   1481.0868  ...   
4                3452.903892            0.117961    0.069078   1424.5352  ...   
...                      ...                 ...         ...         ...  ...   
16143            3882.812500            0.116425    0.088527   1458.0010  ...   
16144            3816.685268            0.110338    0.067830   1538.0670  ...   
16145            3728.759766            0.105142    0.073135   1637.4955  ...   
16146            3524.797712            0.094456    0.071088   1453.4177  ...   
16147            3375.034877            0.092815    0.062664   1479.7195  ...   

       mfcc_9_std  mfcc_10_mean  mfcc_10_std  mfcc_11_mean  mfcc_11_std  \
0       21.736240      2.303085     8.983318    -17.410305     9.115154   
1       13.937135     -0.953942    10.831742     -0.088775    10.297690   
2       14.900779      0.260098    14.031009     -0.420670    10.810292   
3       15.957924     -1.486122    14.461978     -8.479608    12.550333   
4       15.105562     -3.366364    13.943447     -6.561539    11.944948   
...           ...           ...          ...           ...          ...   
16143   12.486454     -4.034742    13.771613     -5.278946    14.380637   
16144   12.727633     -2.590058    15.919325     -6.724170    14.858981   
16145   12.606261     -0.207149    15.909226     -9.772965    18.003307   
16146   11.453891     -2.735264    15.467333     -4.670631    12.668987   
16147   11.104643     -1.721383    13.189034    -10.234873    15.319916   

       mfcc_12_mean  mfcc_12_std  mfcc_13_mean  mfcc_13_std  label  
0          0.301804    10.452693     -3.080832    10.146248      0  
1         -7.281142    10.926579     -0.450248   

In [6]:
df.duplicated().sum()

0

In [7]:
df['label'].value_counts()

label
1    9841
0    5229
Name: count, dtype: int64

In [8]:
x = df.drop('label', axis = 1)
y = df['label']

In [9]:
x

mean_spectral_centroid  std_spectral_centroid  mean_spectral_bandwidth  \
0                 2247.331739            1158.537748              1870.415462   
1                 1790.719889             996.554825              1757.898617   
2                 1977.923363            1010.148667              1747.099555   
3                 2037.765550            1311.440630              1745.224852   
4                 1739.383829            1092.623322              1623.135563   
...                       ...                    ...                      ...   
16143             1879.614568            1092.394432              1802.821290   
16144             1810.603695            1124.628905              1829.785209   
16145             1820.216958            1197.520780              1770.716715   
16146             1636.619660            1055.832051              1747.968472   
16147             1604.684012            1023.600709              1702.723635   

       std_spectral_bandwidth  mean_spectral_contrast  mean_spectral_flatness  \
0                  370.405241               21.440710                0.036879   
1                  410.710318               21.513383                0.018936   
2                  461.458379               20.476283                0.032616   
3                  419.056484               19.516014                0.028482   
4                  450.088465               20.260620                0.025737   
...                       ...                     ...                     ...   
16143              479.751352               19.930251                0.017547   
16144              491.274993               19.115077                0.017356   
16145              509.906085               19.506173                0.015819   
16146              500.649272               19.118411                0.014007   
16147              555.133862               19.279221                0.016868   

       mean_spectral_rolloff  zero_crossing_rate  rms_energy  mean_pitch  ...  \
0                4419.438073            0.169241    0.082552   1592.1033  ...   
1                3635.742188            0.108068    0.055477   1112.6351  ...   
2                3873.291016            0.144633    0.060388   1557.5225  ...   
3                3826.584507            0.148933    0.029559   1481.0868  ...   
4                3452.903892            0.117961    0.069078   1424.5352  ...   
...                      ...                 ...         ...         ...  ...   
16143            3882.812500            0.116425    0.088527   1458.0010  ...   
16144            3816.685268            0.110338    0.067830   1538.0670  ...   
16145            3728.759766            0.105142    0.073135   1637.4955  ...   
16146            3524.797712            0.094456    0.071088   1453.4177  ...   
16147            3375.034877            0.092815    0.062664   1479.7195  ...   

       mfcc_9_mean  mfcc_9_std  mfcc_10_mean  mfcc_10_std  mfcc_11_mean  \
0       -22.768066   21.736240      2.303085     8.983318    -17.410305   
1        -5.951458   13.937135     -0.953942    10.831742     -0.088775   
2        -6.923712   14.900779      0.260098    14.031009     -0.420670   
3        -0.099328   15.957924     -1.486122    14.461978     -8.479608   
4       -14.372540   15.105562     -3.366364    13.943447     -6.561539   
...            ...         ...           ...          ...           ...   
16143    -1.018675   12.486454     -4.034742    13.771613     -5.278946   
16144    -1.210876   12.727633     -2.590058    15.919325     -6.724170   
16145     1.497070   12.606261     -0.207149    15.909226     -9.772965   
16146     1.224566   11.453891     -2.735264    15.467333     -4.670631   
16147     2.338625   11.104643     -1.721383    13.189034    -10.234873   

       mfcc_11_std  mfcc_12_mean  mfcc_12_std  mfcc_13_mean  mfcc_13_std  
0         9.115154      0.301804    10.452693     -3.080832    10.146248  
1        10.297690     -7.281142    1

In [47]:
y.shape

(15070,)

In [11]:
x.describe()

mean_spectral_centroid  std_spectral_centroid  mean_spectral_bandwidth  \
count            15070.000000           15070.000000             15070.000000   
mean              1701.384153            1018.110186              1584.749875   
std                317.899605             285.942121               128.309386   
min                719.559285             194.998983              1106.939002   
25%               1462.411426             817.940317              1502.170289   
50%               1692.912130            1040.257378              1584.254283   
75%               1914.255553            1225.857413              1667.967754   
max               3059.390150            1912.173446              2046.070801   

       std_spectral_bandwidth  mean_spectral_contrast  mean_spectral_flatness  \
count            15070.000000            15070.000000            15070.000000   
mean               428.708065               20.350168                0.022640   
std                 75.195519                1.659254                0.009914   
min                199.321584               15.154801                0.001816   
25%                378.987364               19.696228                0.015253   
50%                421.364247               20.734723                0.021228   
75%                472.578414               21.504851                0.028573   
max                724.361505               24.907725                0.072172   

       mean_spectral_rolloff  zero_crossing_rate    rms_energy    mean_pitch  \
count           15070.000000        15070.000000  15070.000000  15070.000000   
mean             3268.907144            0.116748      0.084099   1452.435740   
std               532.560286            0.037657      0.022540    289.350721   
min              1310.661765            0.027727      0.022425    359.391170   
25%              2890.701572            0.088303      0.067177   1268.347100   
50%              3279.389303            0.115117      0.082656   1473.799850   
75%              3627.881779            0.142590      0.099309   1655.827250   
max              5451.099537            0.270710      0.187577   2454.724000   

       ...   mfcc_9_mean    mfcc_9_std  mfcc_10_mean   mfcc_10_std  \
count  ...  15070.000000  15070.000000  15070.000000  15070.000000   
mean   ...     -8.158966     13.579835     -0.354899     12.493800   
std    ...      6.178916      2.477078      5.660750      2.335347   
min    ...    -31.488497      5.826506    -20.188465      5.459179   
25%    ...    -12.864778     11.875185     -4.379518     10.753674   
50%    ...     -7.903979     13.348467     -0.365365     12.273242   
75%    ...     -3.485740     15.123625      3.394877     14.062226   
max    ...     10.305757     26.693924     19.610289     22.717190   

       mfcc_11_mean   mfcc_11_std  mfcc_12_mean   mfcc_12_std  mfcc_13_mean  \
count  15070.000000  15070.000000  15070.000000  15070.000000  15070.000000   
mean      -8.759508     11.031914      0.752369      9.716857     -6.490542   
std        5.378700      1.906687      4.308970      1.820020      4.070429   
min      -26.082537      5.594748    -13.585977      4.378153    -26.402317   
25%      -12.522636      9.673325     -2.179148      8.422898     -9.454068   
50%       -8.492837     10.854513      0.846666      9.588833     -6.230590   
75%       -5.022693     12.222374      3.741092     10.886566     -3.378730   
max        6.013963     19.685654     16.436730     17.380630      6.187790   

        mfcc_13_std  
count  15070.000000  
mean       9.545742  
std        1.572650  
min        4.686154  
25%        8.443469  
50%        9.447487  
75%       10.519854  
max       17.941544  

[8 rows x 43 columns]

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [40]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [41]:
selector = SelectKBest(score_func=f_classif, k=15)
x_train_selected = selector.fit_transform(x_train_scaled, y_train)
x_test_selected = selector.transform(x_test_scaled)

In [50]:
df['label'].value_counts()

label
1    9841
0    5229
Name: count, dtype: int64

In [42]:
sm = SMOTE(random_state=42)
x_train_balanced, y_train_balanced = sm.fit_resample(x_train_selected, y_train)

In [16]:
print('Before resampling', format(sum(y_train == 1)))
print('Before resampling', format(sum(y_train == 0)))

Before resampling 6906
Before resampling 3643


In [17]:
print('Before resampling', format(sum(y_train_balanced == 1)))
print('Before resampling', format(sum(y_train_balanced == 0)))

Before resampling 6906
Before resampling 6906


In [19]:
randomModel = RandomForestClassifier()
randomModel.fit(x_train_balanced, y_train_balanced)

RandomForestClassifier()

In [20]:
y_pred = randomModel.predict(x_train_balanced)
y_pred_test = randomModel.predict(x_test_fs)

In [21]:
print(classification_report(y_train_balanced, y_pred))
print(confusion_matrix(y_train_balanced, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6906
           1       1.00      1.00      1.00      6906

    accuracy                           1.00     13812
   macro avg       1.00      1.00      1.00     13812
weighted avg       1.00      1.00      1.00     13812

[[6906    0]
 [   0 6906]]


In [22]:
print(classification_report(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1586
           1       0.99      0.99      0.99      2935

    accuracy                           0.98      4521
   macro avg       0.98      0.98      0.98      4521
weighted avg       0.98      0.98      0.98      4521

[[1547   39]
 [  39 2896]]


In [23]:
neuralModel = MLPClassifier(hidden_layer_sizes=100, max_iter=300, random_state=42)
neuralModel.fit(x_train_balanced, y_train_balanced)

MLPClassifier(hidden_layer_sizes=100, max_iter=300, random_state=42)

In [27]:
y_pred_neural = neuralModel.predict(x_train_balanced)
y_pred_test_neural = neuralModel.predict(x_test_fs)

In [28]:
print(classification_report(y_test, y_pred_test_neural))
print(confusion_matrix(y_test, y_pred_test_neural))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1586
           1       0.99      0.99      0.99      2935

    accuracy                           0.99      4521
   macro avg       0.99      0.99      0.99      4521
weighted avg       0.99      0.99      0.99      4521

[[1563   23]
 [  17 2918]]


In [30]:
print(classification_report(y_train_balanced, y_pred_neural))
print(confusion_matrix(y_train_balanced, y_pred_neural))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6906
           1       1.00      1.00      1.00      6906

    accuracy                           1.00     13812
   macro avg       1.00      1.00      1.00     13812
weighted avg       1.00      1.00      1.00     13812

[[6906    0]
 [   4 6902]]


In [44]:
# Train model
svc_model = SVC(kernel='linear', probability=True)
svc_model.fit(x_train_balanced, y_train_balanced)

SVC(kernel='linear', probability=True)

In [35]:
y_pred_svc = svc_model.predict(x_train_balanced)
y_pred_svc_test = svc_model.predict(x_test_fs)

In [36]:
print(classification_report(y_train_balanced, y_pred_svc))
print(confusion_matrix(y_train_balanced, y_pred_svc))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      6906
           1       0.97      0.96      0.97      6906

    accuracy                           0.97     13812
   macro avg       0.97      0.97      0.97     13812
weighted avg       0.97      0.97      0.97     13812

[[6677  229]
 [ 242 6664]]


In [37]:
print(classification_report(y_test, y_pred_svc_test))
print(confusion_matrix(y_test, y_pred_svc_test))

              precision    recall  f1-score   support

           0       0.93      0.96      0.95      1586
           1       0.98      0.96      0.97      2935

    accuracy                           0.96      4521
   macro avg       0.96      0.96      0.96      4521
weighted avg       0.96      0.96      0.96      4521

[[1526   60]
 [ 109 2826]]


In [46]:
save_path = r"D:\Data science Course\My projects\Guvi projects\vocal_gender_features_new"

with open(os.path.join(save_path, 'svm_model.pkl'), 'wb') as f:
    pickle.dump(svc_model, f)

with open(os.path.join(save_path, 'scaler.pkl'), 'wb') as f:
    pickle.dump(scaler, f)

with open(os.path.join(save_path, 'selectk.pkl'), 'wb') as f:
    pickle.dump(selector, f)

print("✅ Saved new model, scaler, and selector — all matched to 15 features.")

✅ Saved new model, scaler, and selector — all matched to 15 features.
